apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxora-hotel-deployment
  labels:
    app: luxora-hotel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: luxora-hotel
  template:
    metadata:
      labels:
        app: luxora-hotel
    spec:
      containers:
      - name: luxora-website
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
